env:
  browser: true
  commonjs: true
  es6: true
  jest/globals: true
extends: 
  - 'eslint:recommended'
  - 'google'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules: 
  "no-console": "off"
